### ISSUE TITLE
Incorrect Minecraft version declaration in fabric.mod.json

### ISSUE THREAD

**Issue by supersaiyansubtlety** [LudoCrypt/CarveMyPumpkin#1]
This mod crashes on 1.16.1, but it has
```json
"depends": {
	//...
	"minecraft": "1.16.x"
},
```
in `fabric.mod.json`. 
On CurseForge it's only marked as compatible with 1.16.3, so I assume this should be changed to `"minecraft": "1.16.3"` or something.

**Comment by LudoCrypt** [comment]
I haven't actually tested on other versions, so they aren't marked for the other versions on curse yet. But for the sake of not wanting to update the mod each time I check, I leave it at .x. If people follow it for only 1.16.3 then it should be fine, and if it crashes on a different version, it would be their fault for not playing on the right, marked version.

**Comment by supersaiyansubtlety** [comment]
The point of `fabric.mod.json` is to tell users if there's a version miss-match, but do what you want.
