### ISSUE TITLE
The patterns I carved on pumpkin disappears until I break it and place it to the ground again.

### ISSUE THREAD

**Issue by linzexin022** [LudoCrypt/CarveMyPumpkin#2]
Game version: 1.16.3
Fabric Modloader version: 0.10.0+build.208
Fabric API version: 0.23.0+build.410-1.16
Mod version: 1.0.2

Hi there, I found that the patterns I carved on pumpkin disappears when I re-enter the single player game. I have to break it and place it to the ground again to let it show.

![2020-10-09_11 14 19](https://user-images.githubusercontent.com/59003232/95541046-e14dba00-0a24-11eb-8175-2b693bf235cf.png)
![2020-10-09_11 15 56](https://user-images.githubusercontent.com/59003232/95541048-e14dba00-0a24-11eb-96c0-dadeb74a87fd.png)

Tested it with Fabric API only, this situation happened again.

**Comment by LudoCrypt** [comment]
This is going to be fixed along with the next update! Thank you for reporting!
